version: '3.8'
services:

  oracle-db:
    image: gvenzl/oracle-xe
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: root
      APP_USER: system
      APP_USER_PASSWORD: root
    healthcheck:
      test: ["CMD", "echo", "SELECT 1 FROM DUAL;", "|", "sqlplus", "system/root@xe"]
      interval: 10s
      retries: 10

  usuario-service:
    build: .
    container_name: usuario-service
    depends_on:
      - oracle-db
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521:xe
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - tienda-net

networks:
  tienda-net:
    driver: bridge
